name: Deploy

on:
  workflow_call:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
      major_version:
        description: 'Prowlarr major version'
        type: string
        required: true
      version:
        description: 'Prowlarr version'
        type: string
        required: true

jobs:
  release:
    # needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: _artifacts
        pattern: Prowlarr.*
        merge-multiple: true

    - name: Get Previous Release
      id: previous-release
      uses: cardinalby/git-get-release-action@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        latest: true
        prerelease: ${{ inputs.branch != 'sourcerarr' }}

    - name: Generate Release Notes
      id: generate-release-notes
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        result-encoding: string
        script: |
          const { data } = await github.rest.repos.generateReleaseNotes({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ inputs.version }}',
            target_commitish: '${{ github.sha }}',
            previous_tag_name: '${{ steps.previous-release.outputs.tag_name }}',
          })
          return data.body

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: _artifacts/Prowlarr.*
        commit: ${{ github.sha }}
        generateReleaseNotes: false
        body: ${{ steps.generate-release-notes.outputs.result }}
        name: ${{ inputs.version }}
        prerelease: ${{ inputs.branch != 'sourcerarr' }}
        skipIfReleaseExists: true
        tag: v${{ inputs.version }}
