name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - sourcerarr
    paths-ignore:
      - .github
      - src/Prowlarr.Api.*/openapi.json
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github
      - src/NzbDrone.Core/Localization/Core
      - src/Prowlarr.Api.*/openapi.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FRAMEWORK: net6.0
  RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  PROWLARR_MAJOR_VERSION: 0
  VERSION: 0.1.0
  NODE: '20.X'

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Set Version
      id: variables
      run: |
        # Add 800 to the build number because GitHub won't let us pick an arbitrary starting point
        echo "PROWLARR_VERSION=${{ env.VERSION }}.$((${{ github.run_number }}+800))" >> $GITHUB_ENV
  envtest1:
    needs: [versioning]
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "$PROWLARR_VERSION"
    - name: test2
      run: |
        echo "$BLABLA"
      env:
        BLABLA: hello
    - name: test3
      run: |
        echo "${{ env.PROWLARR_VERSION }}"
    - name: test4
      run: |
        echo "$BLABLA"
      env:
        BLABLA: ${{ env.PROWLARR_VERSION }}
  backend:
    needs: [versioning]
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build_target: linux-x64
            artifact_name: linux
    secrets: inherit
    uses: ./.github/workflows/backend.yml
    with:
      os: ${{ matrix.os }}
      build_target: ${{ matrix.build_target }}
      artifact_name: ${{ matrix.artifact_name }}
      dotnet_version: '6.0.421'
      framework: "net6.0"
  frontend:
    needs: [versioning]
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux
    secrets: inherit
    uses: ./.github/workflows/frontend.yml
    with:
      os: ${{ matrix.os }}
      node_version: '20.X'
      artifact_name: ${{ matrix.artifact_name }}
  package:
    needs: [versioning, backend, frontend]
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build_target: linux-x64
            artifact_name: linux
    secrets: inherit
    uses: ./.github/workflows/package.yml
    with:
      os: ${{ matrix.os }}
      build_target: ${{ matrix.build_target }}
      artifact_name: ${{ matrix.artifact_name }}
      dotnet_version: '6.0.421'
      release_version: ${{ github.env.PROWLARR_VERSION }}
      framework: "net6.0"
  deploy:
    needs: [versioning, backend, frontend, package]
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      framework: "net6.0"
      branch: ${{ github.ref_name }}
      major_version: ${{ github.env.PROWLARR_MAJOR_VERSION }}
      version: ${{ github.env.PROWLARR_VERSION }}
