name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - sourcerarr
    paths-ignore:
      - .github
      - src/Prowlarr.Api.*/openapi.json
  pull_request:
    branches:
      - develop
    paths-ignore:
      - .github
      - src/NzbDrone.Core/Localization/Core
      - src/Prowlarr.Api.*/openapi.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FRAMEWORK: net6.0
  RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  PROWLARR_MAJOR_VERSION: 0
  VERSION: 0.1.0
  NODE: '20.X'

jobs:
  backend:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            publish-folder: linux-x64
            publish-label: linux
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set RID and FRAMEWORK
      run: |
        echo "RID=${{ matrix.publish-folder }}" >> $GITHUB_ENV
        echo "FRAMEWORK=net6.0" >> $GITHUB_ENV
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.421'
    - name: Build Backend
      shell: bash
      run: ./build.sh --backend
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-build
        path: _output/
    - name: Publish Test Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-tests
        path: _tests/
  frontend:
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            publish-folder: linux-x64
            publish-label: linux
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE }}
    - name: Build Frontend
      shell: bash
      run: ./build.sh --frontend
      env:
        FORCE_COLOR: 0
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-frontend
        path: _output/
  package:
    needs: [backend, frontend]
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            publish-folder: linux-x64
            publish-label: linux
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set RID and FRAMEWORK
      run: |
        echo "RID=${{ matrix.publish-folder }}" >> $GITHUB_ENV
        echo "FRAMEWORK=net6.0" >> $GITHUB_ENV
    - name: Check out
      uses: actions/checkout@v4
    - name: Download Backend Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-build
        path: _output/
    - name: Download Frontend Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-frontend
        path: _output/
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.421'
    - name: Package
      shell: bash
      run: ./build.sh --packages
    - name: Publish Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.publish-label }}-package
        path: _artifacts/
